name: fooderlich
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  webview_flutter: ^3.0.4
  # For secure password hashing
  crypto: ^3.0.3
  # For more secure storage options
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
    - assets/fooderlich_assets/

